sudo: required

services:
  - docker

before_install:
  - docker info
  - docker build -t mar-kub/docker-gitlab-ci-multi-runner-c-cpp .

script:
  - docker run -it mar-kub/docker-gitlab-ci-multi-runner-c-cpp gcc -v
  - docker run -it mar-kub/docker-gitlab-ci-multi-runner-c-cpp g++ -v