sudo: required

services:
  - docker

before_install:
  - docker info
  - docker build -t mar-kub/docker-c-cpp-build .

script:
  - docker run -it mar-kub/docker-c-cpp-build gcc -v
  - docker run -it mar-kub/docker-c-cpp-build g++ -v